server {
    listen 80;
    server_name lusworkshop.site;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name lusworkshop.site;

    ssl_certificate          /ssl/lusworkshop.site.crt;
    ssl_certificate_key      /ssl/lusworkshop.site.key;

    # SSL hardening
    ssl_protocols            TLSv1.2 TLSv1.3;
    ssl_ciphers              HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Fix mixed content warning
    add_header Content-Security-Policy "upgrade-insecure-requests;";

    # Optional but recommended security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options SAMEORIGIN;

    client_max_body_size 50m;

    location / {
        proxy_pass         http://fms:3000;
        proxy_buffer_size          32k;
        proxy_buffers              8 32k;
        proxy_busy_buffers_size    64k;

        # 保持头信息
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket 支持
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        client_max_body_size 50m;
    }

    location = /static/ {
        root   /static;
    }

    location /oauth2/ {
        proxy_pass http://oauth2:22001;

        # 保持头信息
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket 支持
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}